In [3]:
lst = [1, 2, 3, 4]

print(lst * 3 ) # list does not support whole array computation

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr, type(arr))

print(arr * 2) # ndarray supports whole array computation

[1 2 3 4] <class 'numpy.ndarray'>
[2 4 6 8]


### Dimensions of ndarray

In [5]:
arr1d = np.array([1, 2, 3]) # single row or vector
arr2d = np.array([ # array inside array | a sheet of paper
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
arr3d = np.array([ # whole building
    [ # 1st floor of the building
        [1, 2, 3], # 1st apartment on 1st floor
        [4, 5, 6]
    ], 
    [ # 2nd floor 
        [7, 8, 9], # 1st aptment on 2nd floor
        [10, 11, 12]
    ]
])

### Attributes of ndarray

In [6]:
print(arr1d.ndim, arr2d.ndim, arr3d.ndim) # .ndim
print(arr1d.shape, arr2d.shape, arr3d.shape) # .shape
print(arr1d.size, arr2d.size, arr3d.size) # .size | total element count

1 2 3
(3,) (3, 3) (2, 2, 3)
3 9 12


### Datatypes of   ndarray 

In [7]:
arr = np.array([1, 2, 3])
print(arr.dtype)

arr = np.array([1.1, 2.2, 3.3])
print(arr.dtype)

arr = np.array(['aaaaa', 'bbb'])
print(arr.dtype)

int64
float64
<U5


In [8]:
arr = np.array([1, 2, 3.3]) # upcasted to float
print(arr.dtype)

arr = np.array([1, 1.4, False, 2, '3']) # upcasted to string
print(arr.dtype)


float64
<U32


### Selecting datatype for an array

In [9]:
arr = np.array([1, 2, 30])
print(arr.dtype)

arr = np.array([1, 3, 5], dtype=np.int8)
print(arr.dtype)

# arr = np.array([1, 3, 128], dtype=np.int8) # int8 supports -128 to 127 only
# print(arr.dtype)

arr = arr.astype(np.float64) # ndarray.astype()
print(arr)
print(type(arr))
print(arr.dtype)


int64
int8
[1. 3. 5.]
<class 'numpy.ndarray'>
float64


### Creating ndarray from existing data

In [10]:
lst = [1, 2, 3]

arr = np.array(lst)
print(arr)
print(arr.dtype)

arr = np.array(lst, dtype=np.float64)
print(arr.dtype)

mixed_lst = [1, 3.3, 'asdf'] # Upcasting happens
arr = np.array(mixed_lst)
print(arr.dtype)


[1 2 3]
int64
float64
<U32


In [11]:
matrix = [
    [1,2,3],
    [4,5,6]
]

arr = np.array(matrix)

print(arr)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
int64


In [12]:
tuple = (1, 2,3)

print(tuple)
print(type(tuple))

arr = np.array(tuple, dtype=np.float32)
print(type(arr))

(1, 2, 3)
<class 'tuple'>
<class 'numpy.ndarray'>


In [13]:
set = {1,2,3} # set is abnormal, rather convert to list
print(set)
print(type(set))

arr = np.array(set)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)

{1, 2, 3}
<class 'set'>
{1, 2, 3}
<class 'numpy.ndarray'>
object
0
()
1


In [14]:
arr = np.array(list(set))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[1 2 3]
<class 'numpy.ndarray'>
int64
1
(3,)
3


In [15]:
# from dictionary
dct = {'a': 1, 'b': 2, 'c': 3}

keys = dct.keys()
values = dct.values()
items = dct.items()

print(keys)
print(values)
print(items)

arr = np.array(dct) # direct dict input is wrong approach

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)

dict_keys(['a', 'b', 'c'])
dict_values([1, 2, 3])
dict_items([('a', 1), ('b', 2), ('c', 3)])
{'a': 1, 'b': 2, 'c': 3}
<class 'numpy.ndarray'>
object
0
()
1


In [16]:
arr = np.array(keys)
print('\n', arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)

arr = np.array(values)
print('\n', arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)

arr = np.array(items)
print('\n', arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)


 dict_keys(['a', 'b', 'c'])
<class 'numpy.ndarray'>
object
()
1

 dict_values([1, 2, 3])
<class 'numpy.ndarray'>
object
()
1

 dict_items([('a', 1), ('b', 2), ('c', 3)])
<class 'numpy.ndarray'>
object
()
1


In [17]:

arr = np.array(list(keys)) # initialize after converting to list
print('\n', arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)

arr = np.array(list(values))
print('\n', arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)

arr = np.array(list(items))
print('\n', arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)


 ['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
3

 [1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
3

 [['a' '1']
 ['b' '2']
 ['c' '3']]
<class 'numpy.ndarray'>
<U21
(3, 2)
6


### ndarray generation with random value

In [ ]:
arr = np.random.rand(2,3) # outputs random float b/w 0-1
print(arr)
print(arr.dtype)

arr = np.random.randint(10, 20, (2, 3)) # integer
print(arr)
print(arr.dtype)

np.random.uniform(10, 20, (3,4)) # floating point


[[0.46816759 0.70266235 0.35938509]
 [0.08800528 0.81379096 0.01589699]]
float64
[[18 14 16]
 [19 16 15]]
int32


array([[17.14851129, 16.47664441, 15.95764738, 14.28325275],
       [13.04891135, 14.68054655, 15.3750576 , 10.21833966],
       [13.84756174, 19.69195683, 11.75080474, 10.83520855]])