In [1]:
lst = [1, 2, 3, 4]

print(lst * 3 ) # list does not support whole array computation

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr, type(arr))

print(arr * 2) # ndarray supports whole array computation

[1 2 3 4] <class 'numpy.ndarray'>
[2 4 6 8]


### Dimensions of ndarray

In [3]:
arr1d = np.array([1, 2, 3]) # single row or vector
arr2d = np.array([ # array inside array | a sheet of paper
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
arr3d = np.array([ # whole building
    [ # 1st floor of the building
        [1, 2, 3], # 1st apartment on 1st floor
        [4, 5, 6]
    ], 
    [ # 2nd floor 
        [7, 8, 9], # 1st aptment on 2nd floor
        [10, 11, 12]
    ]
])

### Attributes of ndarray

In [4]:
print(arr1d.ndim, arr2d.ndim, arr3d.ndim) # .ndim
print(arr1d.shape, arr2d.shape, arr3d.shape) # .shape
print(arr1d.size, arr2d.size, arr3d.size) # .size | total element count

1 2 3
(3,) (3, 3) (2, 2, 3)
3 9 12


### Datatypes of   ndarray 

In [5]:
arr = np.array([1, 2, 3])
print(arr.dtype)

arr = np.array([1.1, 2.2, 3.3])
print(arr.dtype)

arr = np.array(['aaaaa', 'bbb'])
print(arr.dtype)

int64
float64
<U5


In [6]:
arr = np.array([1, 2, 3.3]) # upcasted to float
print(arr.dtype)

arr = np.array([1, 1.4, False, 2, '3']) # upcasted to string
print(arr.dtype)


float64
<U32


### Selecting datatype for an array

In [7]:
arr = np.array([1, 2, 30])
print(arr.dtype)

arr = np.array([1, 3, 5], dtype=np.int8)
print(arr.dtype)

# arr = np.array([1, 3, 128], dtype=np.int8) # int8 supports -128 to 127 only
# print(arr.dtype)

arr = arr.astype(np.float64) # ndarray.astype()
print(arr)
print(type(arr))
print(arr.dtype)


int64
int8
[1. 3. 5.]
<class 'numpy.ndarray'>
float64


### Creating ndarray from existing data

In [8]:
lst = [1, 2, 3]

arr = np.array(lst)
print(arr)
print(arr.dtype)

arr = np.array(lst, dtype=np.float64)
print(arr.dtype)

mixed_lst = [1, 3.3, 'asdf'] # Upcasting happens
arr = np.array(mixed_lst)
print(arr.dtype)


[1 2 3]
int64
float64
<U32


In [9]:
matrix = [
    [1,2,3],
    [4,5,6]
]

arr = np.array(matrix)

print(arr)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
int64


In [10]:
tuple = (1, 2,3)

print(tuple)
print(type(tuple))

arr = np.array(tuple, dtype=np.float32)
print(type(arr))

(1, 2, 3)
<class 'tuple'>
<class 'numpy.ndarray'>


In [11]:
set = {1,2,3} # set is abnormal, rather convert to list
print(set)
print(type(set))

arr = np.array(set)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)

{1, 2, 3}
<class 'set'>
{1, 2, 3}
<class 'numpy.ndarray'>
object
0
()
1


In [12]:
arr = np.array(list(set))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[1 2 3]
<class 'numpy.ndarray'>
int64
1
(3,)
3


In [13]:
# from dictionary
dct = {'a': 1, 'b': 2, 'c': 3}

keys = dct.keys()
values = dct.values()
items = dct.items()

print(keys)
print(values)
print(items)

arr = np.array(dct) # direct dict input is wrong approach

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)

dict_keys(['a', 'b', 'c'])
dict_values([1, 2, 3])
dict_items([('a', 1), ('b', 2), ('c', 3)])
{'a': 1, 'b': 2, 'c': 3}
<class 'numpy.ndarray'>
object
0
()
1


In [14]:
arr = np.array(keys)
print('\n', arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)

arr = np.array(values)
print('\n', arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)

arr = np.array(items)
print('\n', arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)


 dict_keys(['a', 'b', 'c'])
<class 'numpy.ndarray'>
object
()
1

 dict_values([1, 2, 3])
<class 'numpy.ndarray'>
object
()
1

 dict_items([('a', 1), ('b', 2), ('c', 3)])
<class 'numpy.ndarray'>
object
()
1


In [15]:

arr = np.array(list(keys)) # initialize after converting to list
print('\n', arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)

arr = np.array(list(values))
print('\n', arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)

arr = np.array(list(items))
print('\n', arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)


 ['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
3

 [1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
3

 [['a' '1']
 ['b' '2']
 ['c' '3']]
<class 'numpy.ndarray'>
<U21
(3, 2)
6


### ndarray generation with random value

In [16]:
arr = np.random.rand(2,3) # outputs random float b/w 0-1
print(arr)
print(arr.dtype)

arr = np.random.randint(10, 20, (2, 3)) # integer
print(arr)
print(arr.dtype)

np.random.uniform(10, 20, (3,4)) # floating point


[[0.33856531 0.47980095 0.18715229]
 [0.74933166 0.75065217 0.69458972]]
float64
[[12 19 18]
 [10 18 16]]
int32


array([[18.72417119, 17.90067476, 17.52157175, 12.61721526],
       [10.15835886, 13.72733759, 17.27311159, 19.47363246],
       [14.68140126, 15.68439565, 17.19813139, 10.26559606]])

### Generate ndarray from range

In [17]:
arr = np.arange(2, 11, 1)
print(arr)

mat = arr.reshape(3, 3)
print(mat)

[ 2  3  4  5  6  7  8  9 10]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [18]:
arr_lin = np.linspace(1, 10, 11)
print(arr_lin)

np.logspace(0, 4, 5)

[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]


array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04])

### Indexing and Slicing

In [19]:
### Indexing

arr1 = np.array([1, 2, 3])
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr[1])
print(arr2[0])

3
[1 2 3]


In [20]:
### Slicing
# 1D array
arr = np.random.randint(1, 100, (10))
print(arr)

arr_view = arr[2:8] # creates a view, not copy
print(arr_view)

arr_view[0] = 10000
print(arr)

arr_copy = arr[2:8].copy() # makes a copy, not reference
print(arr_copy)

arr_copy[0] = -2000
print(arr_copy)
print(arr)

[98 89 13 28 41 94  7 16 56  2]
[13 28 41 94  7 16]
[   98    89 10000    28    41    94     7    16    56     2]
[10000    28    41    94     7    16]
[-2000    28    41    94     7    16]
[   98    89 10000    28    41    94     7    16    56     2]


In [21]:
# 2D array
arr = np.arange(25).reshape(5,5)
print(arr)

print(arr[:3]) # select first 3 rows
print(arr[:, 3:]) # select last 2 cols
print(arr[1:4, 1:4]) # select submatrix from middle

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


### Advanced Indexing

In [22]:
arr = np.arange(10, 20)
print(arr)
# 1D
print(arr[[3,4,8]])

arr = np.arange(9).reshape(3,3)
print(arr)
# 2D
print(arr[[1,1,2], [1,2,2]]) # arr[[all rows], [all cols]] 
# using bools
print(arr[arr>4])

arr[arr>3] = 0
print(arr)

[10 11 12 13 14 15 16 17 18 19]
[13 14 18]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[4 5 8]
[5 6 7 8]
[[0 1 2]
 [3 0 0]
 [0 0 0]]


### Iteration

In [23]:
a = np.arange(9).reshape(3,3)
print(a)

for i in a:
    for j in i:
        print(j)

print(type(np.nditer(a)))

for i in np.nditer(a):
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
0
1
2
3
4
5
6
7
8
<class 'numpy.nditer'>
0
1
2
3
4
5
6
7
8


### Optional Section

### Creating ndarray from Scratch

In [24]:
a = np.zeros((1,3))
print(a)

a = np.zeros((2,3), np.int32)
print(a)

a = np.arange(9).reshape(3,3)
print(a)

a_zeros = np.zeros_like(a)
print(a_zeros)

a_ones = np.ones_like(a)
print(a_ones)

a_3d_ones = np.ones((3,3,3), np.int8)
print(a_3d_ones)

[[0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [25]:
a = np.empty((3,3))
print(a)

a = np.empty_like(a_3d_ones)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[   0    0    0]
  [   0    0    0]
  [   0    0  112]]

 [[ -66 -112   -2]
  [ -55    2    0]
  [   0  112  -61]]

 [[-112   -2  -55]
  [   2    0    0]
  [ -16  -59 -112]]]


In [26]:
a = np.full((3,3), 99)
print(a)

a = np.full((3,3), np.inf)
print(a)

a = np.full_like(a_3d_ones, 3)
print(a)

[[99 99 99]
 [99 99 99]
 [99 99 99]]
[[inf inf inf]
 [inf inf inf]
 [inf inf inf]]
[[[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]]


### Creating matrices

In [27]:
mat_diag = np.diag([1,2,3])
print(mat_diag)

mat_identity = np.eye(3)
print(mat_identity)

mat = np.eye(3,4)
print(mat)

mat = np.eye(3,4, -1)
print(mat)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


### Creating dataset

In [28]:
# given dataset
data = np.arange(30).reshape(10,3)
print(data)

# randomizing dataset
random_indices = np.random.choice(10, (10), replace=False)
print(random_indices)

random_dataset = data[random_indices]
print(random_dataset)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
[0 7 5 6 4 3 2 9 8 1]
[[ 0  1  2]
 [21 22 23]
 [15 16 17]
 [18 19 20]
 [12 13 14]
 [ 9 10 11]
 [ 6  7  8]
 [27 28 29]
 [24 25 26]
 [ 3  4  5]]


In [29]:
# Extraction of Features and Target

X = random_dataset[:, :2] # features
print(X)

y = random_dataset[:, 2:] # target
print(y)

[[ 0  1]
 [21 22]
 [15 16]
 [18 19]
 [12 13]
 [ 9 10]
 [ 6  7]
 [27 28]
 [24 25]
 [ 3  4]]
[[ 2]
 [23]
 [17]
 [20]
 [14]
 [11]
 [ 8]
 [29]
 [26]
 [ 5]]


In [30]:
# Train Test Splitting
train_index = int(len(data) * 0.8)
print(train_index)

print(X)

X_train = X[ : train_index]
print(X_train)

X_test = X[train_index : ]
print(X_test)

y_train = y[:train_index]
y_test = y[train_index:]
print(y_train)
print(y_test)

8
[[ 0  1]
 [21 22]
 [15 16]
 [18 19]
 [12 13]
 [ 9 10]
 [ 6  7]
 [27 28]
 [24 25]
 [ 3  4]]
[[ 0  1]
 [21 22]
 [15 16]
 [18 19]
 [12 13]
 [ 9 10]
 [ 6  7]
 [27 28]]
[[24 25]
 [ 3  4]]
[[ 2]
 [23]
 [17]
 [20]
 [14]
 [11]
 [ 8]
 [29]]
[[26]
 [ 5]]


### Dataset creation using scikitlearn

In [31]:
# !pip install scikit-learn

In [115]:
from sklearn.model_selection import train_test_split

print(X, '\n')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(X_train, X_test, y_train, y_test, sep='\n\n')

[[ 0  1]
 [21 22]
 [15 16]
 [18 19]
 [12 13]
 [ 9 10]
 [ 6  7]
 [27 28]
 [24 25]
 [ 3  4]] 

[[21 22]
 [24 25]
 [12 13]
 [ 0  1]
 [15 16]
 [18 19]
 [ 6  7]
 [ 3  4]]

[[ 9 10]
 [27 28]]

[[23]
 [26]
 [14]
 [ 2]
 [17]
 [20]
 [ 8]
 [ 5]]

[[11]
 [29]]
