### Manipulating ndarray

In [3]:
import numpy as np

## Reshaping

arr = np.arange(20).reshape(4,5)
print(arr)
print(arr.shape)

arr = arr.reshape(2, 10)
print(arr)
print(arr.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
(2, 10)


In [4]:
## Flattening
print(arr.ndim)

arr = arr.flatten()
print(arr)
print(arr.shape)
print(arr.ndim)


2
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)
1


In [8]:
## Raveling
arr = np.arange(20).reshape(4,5)
print(arr)
print(arr.ndim)

flatten_row_wise = arr.ravel()
print(flatten_row_wise)

flatten_col_wise = arr.ravel(order='F')
print(flatten_col_wise)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
2
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  5 10 15  1  6 11 16  2  7 12 17  3  8 13 18  4  9 14 19]


In [21]:
## Concatenation

a1 = np.arange(20).reshape(4,5)
a2 = np.arange(20, 40).reshape(4,5)
print(a1, a2, sep='\n')

concat_row_wise = np.concatenate((a1, a2))
concat_col_wise = np.concatenate((a1, a2), axis=1)
print()
print(concat_row_wise)
print(concat_col_wise)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
[[ 0  1  2  3  4 20 21 22 23 24]
 [ 5  6  7  8  9 25 26 27 28 29]
 [10 11 12 13 14 30 31 32 33 34]
 [15 16 17 18 19 35 36 37 38 39]]


In [24]:
## Transpose

a = np.arange(20).reshape(2,10)
print(a)
print(a.T)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]


In [34]:
## Array Splitting

a = np.arange(20)
print(a)

a_splitted = np.array_split(a, 3)
print(a_splitted)

a_equal_splitted = np.split(a, 4)
print(a_equal_splitted)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[array([0, 1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13]), array([14, 15, 16, 17, 18, 19])]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19])]


### ndarray Arithmetic Operators

In [41]:
a1 = [10, 20, 30, 40, 50]
a2 = [2, 3, 4, 5, 6]

# faster for vectorization
b1 = np.array(a1)
b2 = np.array(a2)

## Operators

print( a1+a1 ) # list concat
print( b1+b2 ) # element wise addition ## np.add(b1, b2)
print()
# print( a1*a2 ) # error multiplying by a list
print( b1*b2 ) # element wise multiplication

print( b1%b2 )

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
[12 23 34 45 56]

[ 20  60 120 200 300]
[0 2 2 0 2]


### Trigonometric Functions

In [ ]:

print(b2)
print(np.sin(b2))
print(np.cos(b2))
print(np.tan(b2))
print(np.rad2deg(b2))


print()
print(b1)
print(np.log10(b1)) # it means -> oi element ke 10 diye koybar vag kora zabe
print(np.log2(b1)) # 2 diye koybar vag kora zabe -> 40 - 20 - 10 - 5 - 2.5 

[2 3 4 5 6]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[-0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
[-2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]
[114.59155903 171.88733854 229.18311805 286.47889757 343.77467708]

[10 20 30 40 50]
[1.         1.30103    1.47712125 1.60205999 1.69897   ]
[3.32192809 4.32192809 4.9068906  5.32192809 5.64385619]
