### Manipulating ndarray

In [3]:
import numpy as np

## Reshaping

arr = np.arange(20).reshape(4,5)
print(arr)
print(arr.shape)

arr = arr.reshape(2, 10)
print(arr)
print(arr.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
(2, 10)


In [4]:
## Flattening
print(arr.ndim)

arr = arr.flatten()
print(arr)
print(arr.shape)
print(arr.ndim)


2
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)
1


In [8]:
## Raveling
arr = np.arange(20).reshape(4,5)
print(arr)
print(arr.ndim)

flatten_row_wise = arr.ravel()
print(flatten_row_wise)

flatten_col_wise = arr.ravel(order='F')
print(flatten_col_wise)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
2
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  5 10 15  1  6 11 16  2  7 12 17  3  8 13 18  4  9 14 19]


In [20]:
## Concatenation

a1 = np.arange(20).reshape(4,5)
a2 = np.arange(20, 40).reshape(4,5)
print(a1, a2, sep='\n')

concat_row_wise = np.concatenate((a1, a2))
concat_col_wise = np.concatenate((a1, a2), axis=1)
print()
print(concat_row_wise)
print(concat_col_wise)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
[[ 0  1  2  3  4 20 21 22 23 24]
 [ 5  6  7  8  9 25 26 27 28 29]
 [10 11 12 13 14 30 31 32 33 34]
 [15 16 17 18 19 35 36 37 38 39]]
