### Manipulating ndarray

In [3]:
import numpy as np

## Reshaping

arr = np.arange(20).reshape(4,5)
print(arr)
print(arr.shape)

arr = arr.reshape(2, 10)
print(arr)
print(arr.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
(2, 10)


In [4]:
## Flattening
print(arr.ndim)

arr = arr.flatten()
print(arr)
print(arr.shape)
print(arr.ndim)


2
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)
1


In [8]:
## Raveling
arr = np.arange(20).reshape(4,5)
print(arr)
print(arr.ndim)

flatten_row_wise = arr.ravel()
print(flatten_row_wise)

flatten_col_wise = arr.ravel(order='F')
print(flatten_col_wise)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
2
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  5 10 15  1  6 11 16  2  7 12 17  3  8 13 18  4  9 14 19]


In [21]:
## Concatenation

a1 = np.arange(20).reshape(4,5)
a2 = np.arange(20, 40).reshape(4,5)
print(a1, a2, sep='\n')

concat_row_wise = np.concatenate((a1, a2))
concat_col_wise = np.concatenate((a1, a2), axis=1)
print()
print(concat_row_wise)
print(concat_col_wise)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
[[ 0  1  2  3  4 20 21 22 23 24]
 [ 5  6  7  8  9 25 26 27 28 29]
 [10 11 12 13 14 30 31 32 33 34]
 [15 16 17 18 19 35 36 37 38 39]]


In [24]:
## Transpose

a = np.arange(20).reshape(2,10)
print(a)
print(a.T)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]


In [34]:
## Array Splitting

a = np.arange(20)
print(a)

a_splitted = np.array_split(a, 3)
print(a_splitted)

a_equal_splitted = np.split(a, 4)
print(a_equal_splitted)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[array([0, 1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13]), array([14, 15, 16, 17, 18, 19])]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19])]


### ndarray Arithmetic Operators

In [41]:
a1 = [10, 20, 30, 40, 50]
a2 = [2, 3, 4, 5, 6]

# faster for vectorization
b1 = np.array(a1)
b2 = np.array(a2)

## Operators

print( a1+a1 ) # list concat
print( b1+b2 ) # element wise addition ## np.add(b1, b2)
print()
# print( a1*a2 ) # error multiplying by a list
print( b1*b2 ) # element wise multiplication

print( b1%b2 )

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
[12 23 34 45 56]

[ 20  60 120 200 300]
[0 2 2 0 2]


### Trigonometric Functions

In [52]:

print(b2)
print(np.sin(b2))
print(np.cos(b2))
print(np.tan(b2))
print(np.rad2deg(b2))


print()
print(b1)
print(np.log10(b1)) # it means -> oi element ke 10 diye koybar vag kora jabe
print(np.log2(b1)) # 2 diye koybar vag kora jabe -> 40 - 20 - 10 - 5 - 2.5
print(np.sqrt(b1)) 

[2 3 4 5 6]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[-0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
[-2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]
[114.59155903 171.88733854 229.18311805 286.47889757 343.77467708]

[10 20 30 40 50]
[1.         1.30103    1.47712125 1.60205999 1.69897   ]
[3.32192809 4.32192809 4.9068906  5.32192809 5.64385619]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [53]:
print(b2)
print(np.sum(b2))
print(np.cumulative_sum(b2))

[2 3 4 5 6]
20
[ 2  5  9 14 20]


### Logical Operator

In [58]:
print(b1)
print(b2)

greater = b1 > b2
print(greater)

equal = b1==b2
print(equal)

print(np.all(greater))
print(np.any(equal))

[10 20 30 40 50]
[2 3 4 5 6]
[ True  True  True  True  True]
[False False False False False]
True
False


### Sorting

In [72]:
# 1D sort
x = np.random.choice(10, 10, replace=False)
print(x)

y = x.copy()
print(y)

y.sort() # inplace sort
print(y)
print(y)
print()

z = np.sort(x) # copy sort
print(z)
print(x)

[8 4 7 3 1 0 9 5 6 2]
[8 4 7 3 1 0 9 5 6 2]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]
[8 4 7 3 1 0 9 5 6 2]


In [84]:
# 2D sort
a = np.random.choice(16, (4,4), replace=False)
print(a)

a_sorted_row_wise = np.sort(a) # row-wise sort (axis=1)
print(a_sorted_row_wise)

a_sorted_col_wise = np.sort(a, axis=0)
print(a_sorted_col_wise)

[[ 8  3  2  7]
 [ 5  9 10 12]
 [ 6  4  0 13]
 [ 1 11 14 15]]
[[ 2  3  7  8]
 [ 5  9 10 12]
 [ 0  4  6 13]
 [ 1 11 14 15]]
[[ 1  3  0  7]
 [ 5  4  2 12]
 [ 6  9 10 13]
 [ 8 11 14 15]]


### Searching 

In [112]:
a = np.array([
    [1, 9, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(a)

print(np.where(a==9)) # returns indices
print(np.where(a<6))

print(np.where(a < 6, a, 0)) # returns array


[[1 9 3]
 [4 5 6]
 [7 8 9]]
(array([0, 2]), array([1, 2]))
(array([0, 0, 1, 1]), array([0, 2, 0, 1]))
[[1 0 3]
 [4 5 0]
 [0 0 0]]


In [131]:
# find out max value index
b = np.random.choice(10, 10)
print(b)
print(np.argmax(b)) # returns max val index
print(np.argmin(b))

[2 3 6 7 9 7 9 2 9 2]
4
0


### Counting

In [143]:
a = np.random.choice(100, (100))
print(a)

print(np.count_nonzero(a>50))
print(np.count_nonzero(a=50))

[31 63 56 85 80 72 59 69 74 30 16  9 95 93 90 18 41 14 70  1 77 83 73 34
 21 33 66 34 28  9 85 30 91  7 17 59 10  6 67 82 19 64 22 78 17  5 24 47
 66 25 10 85  0 73 79 96 69 78 37 99 29 68 54 98 84  3 73 47 91 96 31 61
  9 42 66 89 45 86 43 40  3 78 87  4 26 38 64  4 59 52 24  4 47 10 47 96
 54 57 58 70]
52
1


In [149]:
print(np.unique(a))
unique_val, counts = np.unique(a, return_counts=True)
print(unique_val)
print(counts)

[ 0  1  3  4  5  6  7  9 10 14 16 17 18 19 21 22 24 25 26 28 29 30 31 33
 34 37 38 40 41 42 43 45 47 52 54 56 57 58 59 61 63 64 66 67 68 69 70 72
 73 74 77 78 79 80 82 83 84 85 86 87 89 90 91 93 95 96 98 99]
[ 0  1  3  4  5  6  7  9 10 14 16 17 18 19 21 22 24 25 26 28 29 30 31 33
 34 37 38 40 41 42 43 45 47 52 54 56 57 58 59 61 63 64 66 67 68 69 70 72
 73 74 77 78 79 80 82 83 84 85 86 87 89 90 91 93 95 96 98 99]
[1 1 2 3 1 1 1 3 3 1 1 2 1 1 1 1 2 1 1 1 1 2 2 1 2 1 1 1 1 1 1 1 4 1 2 1 1
 1 3 1 1 2 3 1 1 2 2 1 3 1 1 3 1 1 1 1 1 3 1 1 1 1 2 1 1 3 1 1]


### Statistical Functions

In [160]:
marks = np.genfromtxt('dataset/student_scores.csv', delimiter=',', skip_header=True) # load data
print(marks)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [166]:
marks_math = marks[:, :1]
marks_sci = marks[:, 1:2]
marks_eng = marks[:, 2:]

print(marks_math.T) # transpose it for better view

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]


In [173]:
print(np.max(marks_math))
print(np.min(marks_math))
print(np.average(marks_math))
print(np.mean(marks_math))
print(np.median(marks_math))
print(np.std(marks_math))

95.0
45.0
73.15
73.15
73.5
13.788672887555204


In [182]:
## Correlation
study_hours = np.array([2,4,6,8,9])
marks = np.array([49,55,60,90,99])

table = np.array([study_hours, marks])
print(table)
print(np.corrcoef(table))

[[ 2  4  6  8  9]
 [49 55 60 90 99]]
[[1.         0.94206563]
 [0.94206563 1.        ]]


### Linear Algebra with Numpy

In [187]:
a = np.arange(6).reshape(2,3)
print(a)
b = np.arange(6).reshape(3,2)
print(b)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [229]:
print(np.dot(a,b))
print(np.trace(a))

mat_square = np.random.choice(9, (3,3))
print(mat_square)
print(np.linalg.det(mat_square))
print(np.linalg.matrix_rank(mat_square))

[[10 13]
 [28 40]]
4
[[7 8 3]
 [8 7 4]
 [8 4 0]]
72.0
3
